# Generated by Django 2.2.1 on 2019-05-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_gpx', '0002_auto_20190517_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
